spring:
  application:
    name: hotels-service

  security:
    oauth2:
      resourceserver:
      # TODO Configure resource server to handle token from Keycloak

# Match gateway route port & path
server:
  port: 8082
  servlet:
    context-path: /hotels/
