version: '3'
# from: https://github.com/keycloak/keycloak-containers/blob/main/docker-compose-examples/keycloak-postgres.yml

volumes:
  import:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KC_DB: postgres
      KC_DB_ADDR: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_HTTP_RELATIVE_PATH: /auth
    command: start-dev --import-realm
    ports:
      # Disable 8090 when recording with WireMock
      - 8090:8080
      - 8091:8080
    depends_on:
      - postgres
    volumes:
      - ./import:/opt/keycloak/data/import/:ro

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8100:80
