name: GitHub Pages Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          # pdf_build: true
          asciidoctor_params: --attribute=nofooter
          # slides_build: true
          # pre_build:
          # post_build:
