name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '18' ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Compile all modules
        run: ./mvnw -B -Dstyle.color=always test-compile --file pom.xml
      - name: Test Adding Spring Security module
        run: ./mvnw -B -Dstyle.color=always verify --file adding-spring-security/pom.xml
      - name: Spotless Check
        run: ./mvnw -B -Dstyle.color=always spotless:check
